export type CampusId = "UIC";

export type CampusLocation = {
  id: string;
  campus: CampusId;
  name: string;
  buildingNumber: string;
  code: string;
  address: string;
  access: "public-campus" | "residence" | "venue";
  aliases: string[];
};

export const CAMPUS_CONFIG = {
  UIC: {
    id: "UIC" as const,
    name: "University of Illinois Chicago",
    emailDomain: "uic.edu",
    inviteCodes: ["CLUBPILOT", "UICCLUBS", "CLUSTRUIC"],
  },
};

export const UIC_LOCATIONS: CampusLocation[] = [
  {
    id: "cdrlc",
    campus: "UIC",
    name: "Computer Design Research and Learning Center",
    buildingNumber: "649",
    code: "CDRLC",
    address: "850 W. Taylor Street",
    access: "public-campus",
    aliases: ["computer design", "research and learning center"],
  },
  {
    id: "ses",
    campus: "UIC",
    name: "Science & Engineering South",
    buildingNumber: "619",
    code: "SES",
    address: "845 West Taylor Street",
    access: "public-campus",
    aliases: ["science engineering south"],
  },
  {
    id: "mrh",
    campus: "UIC",
    name: "Marie Robinson Hall",
    buildingNumber: "664",
    code: "MRH",
    address: "811 West Maxwell Street",
    access: "public-campus",
    aliases: ["marie robinson"],
  },
  {
    id: "tbh",
    campus: "UIC",
    name: "Thomas Beckham Hall",
    buildingNumber: "663",
    code: "TBH",
    address: "1250 South Halsted Street",
    access: "residence",
    aliases: ["beckham hall"],
  },
  {
    id: "cgs",
    campus: "UIC",
    name: "Curtis Granderson Stadium",
    buildingNumber: "668",
    code: "CGS",
    address: "900 West Maxwell Street",
    access: "venue",
    aliases: ["baseball stadium", "granderson stadium"],
  },
  {
    id: "jjst",
    campus: "UIC",
    name: "James J. Stukel Towers",
    buildingNumber: "665",
    code: "JJST",
    address: "718 West Rochford Street",
    access: "residence",
    aliases: ["stukel towers"],
  },
  {
    id: "forum",
    campus: "UIC",
    name: "Isadore and Sadie Dorin Forum",
    buildingNumber: "667",
    code: "FORUM",
    address: "725 West Roosevelt Road",
    access: "venue",
    aliases: ["dorin forum", "forum"],
  },
  {
    id: "rrb",
    campus: "UIC",
    name: "Roosevelt Road Building",
    buildingNumber: "621",
    code: "RRB",
    address: "728 West Roosevelt Road",
    access: "public-campus",
    aliases: ["roosevelt"],
  },
  {
    id: "prl",
    campus: "UIC",
    name: "Plant Research Laboratory",
    buildingNumber: "635",
    code: "PRL",
    address: "1020 South Union Street",
    access: "public-campus",
    aliases: ["plant research"],
  },
  {
    id: "eib",
    campus: "UIC",
    name: "Engineering Innovation Building",
    buildingNumber: "629",
    code: "EIB",
    address: "929 West Taylor Street",
    access: "public-campus",
    aliases: ["engineering innovation"],
  },
  {
    id: "erf",
    campus: "UIC",
    name: "Engineering Research Facility",
    buildingNumber: "648",
    code: "ERF",
    address: "842 West Taylor Street",
    access: "public-campus",
    aliases: ["engineering research"],
  },
  {
    id: "selw",
    campus: "UIC",
    name: "Science & Engineering Laboratory West",
    buildingNumber: "608",
    code: "SELW",
    address: "900 West Taylor Street",
    access: "public-campus",
    aliases: ["science engineering lab west"],
  },
  {
    id: "sele",
    campus: "UIC",
    name: "Science & Engineering Laboratory East",
    buildingNumber: "607",
    code: "SELE",
    address: "950 South Halsted Street",
    access: "public-campus",
    aliases: ["science engineering lab east"],
  },
  {
    id: "seo",
    campus: "UIC",
    name: "Science & Engineering Offices",
    buildingNumber: "631",
    code: "SEO",
    address: "851 South Morgan Street",
    access: "public-campus",
    aliases: ["science engineering offices"],
  },
  {
    id: "ah",
    campus: "UIC",
    name: "Addams Hall",
    buildingNumber: "616",
    code: "AH",
    address: "830 South Halsted Street",
    access: "public-campus",
    aliases: ["addams"],
  },
  {
    id: "bh",
    campus: "UIC",
    name: "Burnham Hall",
    buildingNumber: "617",
    code: "BH",
    address: "828 South Halsted Street",
    access: "public-campus",
    aliases: ["burnham"],
  },
  {
    id: "th",
    campus: "UIC",
    name: "Taft Hall",
    buildingNumber: "615",
    code: "TH",
    address: "826 South Halsted Street",
    access: "public-campus",
    aliases: ["taft"],
  },
  {
    id: "lib",
    campus: "UIC",
    name: "Richard J. Daley Library",
    buildingNumber: "609",
    code: "LIB",
    address: "801 South Morgan Street",
    access: "public-campus",
    aliases: ["daley library", "library"],
  },
  {
    id: "lce",
    campus: "UIC",
    name: "Lecture Center Building E",
    buildingNumber: "604E",
    code: "LCE",
    address: "806 South Halsted Street",
    access: "public-campus",
    aliases: ["lecture center e"],
  },
  {
    id: "lcf",
    campus: "UIC",
    name: "Lecture Center Building F",
    buildingNumber: "604F",
    code: "LCF",
    address: "807 South Morgan Street",
    access: "public-campus",
    aliases: ["lecture center f"],
  },
  {
    id: "lcd",
    campus: "UIC",
    name: "Lecture Center Building D",
    buildingNumber: "604D",
    code: "LCD",
    address: "804 South Halsted Street",
    access: "public-campus",
    aliases: ["lecture center d"],
  },
  {
    id: "sce",
    campus: "UIC",
    name: "UIC Student Center East",
    buildingNumber: "605",
    code: "SCE",
    address: "750 South Halsted Street",
    access: "public-campus",
    aliases: ["student center east", "sce"],
  },
  {
    id: "jahd",
    campus: "UIC",
    name: "Jane Addams' Hull-House Dining Hall",
    buildingNumber: "671",
    code: "JAHD",
    address: "800 South Halsted Street",
    access: "public-campus",
    aliases: ["hull house dining", "dining hall"],
  },
  {
    id: "jah",
    campus: "UIC",
    name: "Jane Addams Hull-House Museum",
    buildingNumber: "670",
    code: "JAH",
    address: "800 South Halsted Street",
    access: "public-campus",
    aliases: ["hull house museum"],
  },
  {
    id: "srf",
    campus: "UIC",
    name: "Student Recreation Facility",
    buildingNumber: "630",
    code: "SRF",
    address: "737 South Halsted Street",
    access: "public-campus",
    aliases: ["rec center", "student recreation"],
  },
  {
    id: "lca",
    campus: "UIC",
    name: "Lecture Center Building A",
    buildingNumber: "604A",
    code: "LCA",
    address: "805 South Morgan Street",
    access: "public-campus",
    aliases: ["lecture center a"],
  },
  {
    id: "lcc",
    campus: "UIC",
    name: "Lecture Center Building C",
    buildingNumber: "604C",
    code: "LCC",
    address: "802 South Halsted Street",
    access: "public-campus",
    aliases: ["lecture center c"],
  },
  {
    id: "lh",
    campus: "UIC",
    name: "Lincoln Hall",
    buildingNumber: "614",
    code: "LH",
    address: "707 South Morgan Street",
    access: "public-campus",
    aliases: ["lincoln"],
  },
  {
    id: "sh",
    campus: "UIC",
    name: "Stevenson Hall",
    buildingNumber: "627",
    code: "SH",
    address: "701 South Morgan Street",
    access: "public-campus",
    aliases: ["stevenson"],
  },
  {
    id: "gh",
    campus: "UIC",
    name: "Grant Hall",
    buildingNumber: "612",
    code: "GH",
    address: "703 South Morgan Street",
    access: "public-campus",
    aliases: ["grant"],
  },
  {
    id: "dh",
    campus: "UIC",
    name: "Douglass Hall",
    buildingNumber: "613",
    code: "DH",
    address: "705 South Morgan Street",
    access: "public-campus",
    aliases: ["douglass"],
  },
  {
    id: "scet",
    campus: "UIC",
    name: "UIC Student Center East Tower",
    buildingNumber: "606",
    code: "SCET",
    address: "710 South Halsted Street",
    access: "public-campus",
    aliases: ["student center east tower"],
  },
  {
    id: "srcs",
    campus: "UIC",
    name: "Student Residence and Commons South",
    buildingNumber: "644S",
    code: "SRCS",
    address: "700 South Halsted Street",
    access: "residence",
    aliases: ["commons south"],
  },
  {
    id: "srcn",
    campus: "UIC",
    name: "Student Residence and Commons North",
    buildingNumber: "644N",
    code: "SRCN",
    address: "650 South Halsted Street",
    access: "residence",
    aliases: ["commons north"],
  },
  {
    id: "ads",
    campus: "UIC",
    name: "Architecture and Design Studios",
    buildingNumber: "628",
    code: "ADS",
    address: "845 West Harrison Street",
    access: "public-campus",
    aliases: ["architecture studios", "design studios"],
  },
  {
    id: "srcc",
    campus: "UIC",
    name: "Student Residence and Commons Courtyard",
    buildingNumber: "644C",
    code: "SRCC",
    address: "600 South Halsted Street",
    access: "residence",
    aliases: ["commons courtyard"],
  },
  {
    id: "srcw",
    campus: "UIC",
    name: "Student Residence and Commons West",
    buildingNumber: "644W",
    code: "SRCW",
    address: "901 West Harrison Street",
    access: "residence",
    aliases: ["commons west"],
  },
  {
    id: "jh",
    campus: "UIC",
    name: "Jefferson Hall",
    buildingNumber: "602",
    code: "JH",
    address: "929 West Harrison Street",
    access: "public-campus",
    aliases: ["jefferson"],
  },
  {
    id: "hh",
    campus: "UIC",
    name: "Henry Hall",
    buildingNumber: "626",
    code: "HH",
    address: "935 West Harrison Street",
    access: "public-campus",
    aliases: ["henry"],
  },
  {
    id: "uh",
    campus: "UIC",
    name: "University Hall",
    buildingNumber: "601",
    code: "UH",
    address: "601 South Morgan Street",
    access: "public-campus",
    aliases: ["university hall"],
  },
  {
    id: "bsb",
    campus: "UIC",
    name: "Behavioral Sciences Building",
    buildingNumber: "618",
    code: "BSB",
    address: "1007 West Harrison Street",
    access: "public-campus",
    aliases: ["behavioral sciences"],
  },
  {
    id: "arc",
    campus: "UIC",
    name: "Academic & Residential Complex",
    buildingNumber: "640",
    code: "ARC",
    address: "940 West Harrison Street",
    access: "residence",
    aliases: ["academic residential complex"],
  },
  {
    id: "uict",
    campus: "UIC",
    name: "UIC Theatre",
    buildingNumber: "624",
    code: "UICT",
    address: "1044 West Harrison Street",
    access: "venue",
    aliases: ["theatre", "theater"],
  },
  {
    id: "etmsw",
    campus: "UIC",
    name: "Education, Theatre, Music and Social Work",
    buildingNumber: "623",
    code: "ETMSW",
    address: "1040 West Harrison Street",
    access: "public-campus",
    aliases: ["education theatre music social work"],
  },
  {
    id: "arena",
    campus: "UIC",
    name: "Credit Union 1 Arena",
    buildingNumber: "638",
    code: "ARENA",
    address: "525 South Racine Avenue",
    access: "venue",
    aliases: ["arena"],
  },
  {
    id: "ssb",
    campus: "UIC",
    name: "Student Services Building",
    buildingNumber: "655",
    code: "SSB",
    address: "1200 West Harrison Street",
    access: "public-campus",
    aliases: ["student services"],
  },
];

export function findCampusLocation(locationId?: string | null) {
  return UIC_LOCATIONS.find((location) => location.id === locationId);
}

export function buildLocationLabel(
  location?: Pick<CampusLocation, "name" | "code"> | null,
  room?: string
) {
  if (!location) return "";
  const trimmedRoom = room?.trim();
  return trimmedRoom
    ? `${location.code} ${trimmedRoom} - ${location.name}`
    : `${location.code} - ${location.name}`;
}

export function isAllowedCampusEmail(email: string, campus: CampusId = "UIC") {
  return email.trim().toLowerCase().endsWith(`@${CAMPUS_CONFIG[campus].emailDomain}`);
}

export function isAllowedInviteCode(code: string, campus: CampusId = "UIC") {
  const normalizedCode = code.trim().toUpperCase();
  return CAMPUS_CONFIG[campus].inviteCodes.includes(normalizedCode);
}

export function searchCampusLocations(query: string) {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) return UIC_LOCATIONS;

  return UIC_LOCATIONS.filter((location) => {
    const searchable = [
      location.name,
      location.code,
      location.buildingNumber,
      location.address,
      ...location.aliases,
    ]
      .join(" ")
      .toLowerCase();

    return searchable.includes(normalizedQuery);
  });
}
